version: "3.9"
services:
  flask_app:
    container_name: hist_dk_gni_ng_v4
    build:
      context: .
    ports:
      - "5003:5003"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5003/health"]
      interval: 30s
      timeout: 10s
      retries: 3


  nginx:
    image: nginx:latest
    ports :
      - "8081:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - flask_app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
