version: "3.9"
services:
  flask_app:
    container_name: hist_dk_gni_ng_v2
    build:
      context: .
    ports:
      - "5002:5002"
    networks:
      - app-network


  nginx:
    image: nginx:latest
    ports :
      - "8081:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - flask_app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
