"""created one to many relationship from user to tasks

Revision ID: 0fb9b6ea3141
Revises: 2fc0b68bbc50
Create Date: 2024-10-15 14:35:01.387629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0fb9b6ea3141'
down_revision: Union[str, None] = '2fc0b68bbc50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
